import { PaperProjectType } from "../d";

export const papers: PaperProjectType[] = [
  {
    title:
      "Dengue genetic divergence generates within-serotype antigenic variation, but serotypes dominate evolutionary dynamics.",
    description: "Dengue antigenic evolution & population dynamics",
    imageSource:
      "https://github.com/sidneymbell/sidneymbell.science/blob/main/src/images/dengue_elife_2019.jpg",
    date: "2019",
    authors: "S. Bell, L. Katzelnick, T. Bedford",
    journal: "eLife",
    link: "https://elifesciences.org/articles/42496",
  },
  {
    title: "Estimating Vaccine-Driven Selection in Seasonal Influenza.",
    description: "Whether vaccination effects viral evolution in seasonal flu",
    imageSource:
      "https://github.com/sidneymbell/sidneymbell.science/blob/main/src/images/flu_viruses_2018.png",
    date: "2018",
    authors: "F. Wen, S. Bell, T. Bedford, S. Cobey",
    journal: "Viruses",
    link: "https://www.mdpi.com/1999-4915/10/9/509",
  },
  {
    title:
      "Modern-day SIV viral diversity generated by extensive recombination and cross-species transmission.",
    description: "Paleovirology of ancient cross-species transmissions",
    imageSource:
      "https://github.com/sidneymbell/sidneymbell.science/blob/main/src/images/siv_plospath_2017.jpg",
    date: "2017",
    authors: "S. Bell, T. Bedford",
    journal: "PLoS Pathogens",
    link: "https://journals.plos.org/plospathogens/article?id=10.1371%2Fjournal.ppat.1006466#",
  },
];
