import { ProjectData } from "../d";

export const papers: ProjectData[] = [
  {
    description:
      "Dengue genetic divergence generates within-serotype antigenic variation, but serotypes dominate evolutionary dynamics.",
    title: "Dengue antigenic evolution & population dynamics",
    imageSource:
      "https://raw.githubusercontent.com/sidneymbell/sidneymbell.science/main/src/images/dengue_elife_2019.jpg",
    subtitle: "S. Bell, L. Katzelnick, T. Bedford. eLife 2019.",
    link: "https://elifesciences.org/articles/42496",
    linkText: "Full text",
  },
  {
    description: "Estimating Vaccine-Driven Selection in Seasonal Influenza.",
    title: "Whether vaccination effects viral evolution in seasonal flu",
    imageSource:
      "https://raw.githubusercontent.com/sidneymbell/sidneymbell.science/main/src/images/flu_viruses_2018.png",
    subtitle: "F. Wen, S. Bell, T. Bedford, S. Cobey. Viruses 2018.",
    link: "https://www.mdpi.com/1999-4915/10/9/509",
    linkText: "Full text",
  },
  {
    description:
      "Modern-day SIV viral diversity generated by extensive recombination and cross-species transmission.",
    title: "Paleovirology of ancient cross-species transmissions",
    imageSource:
      "https://raw.githubusercontent.com/sidneymbell/sidneymbell.science/main/src/images/siv_plospath_2017.jpg",
    subtitle: "S. Bell, T. Bedford. PLoS Pathogens 2017.",
    link: "https://journals.plos.org/plospathogens/article?id=10.1371%2Fjournal.ppat.1006466#",
    linkText: "Full text",
  },
];
